### ISSUE TITLE
Suggest a namespace for JiraService

### ISSUE THREAD

**Issue by kalhorim** [kalhorim/JiraService#18]

**Comment by mtss92** [comment]
I suggest the following:
JiraAssistant
JiraFacilitator
JiraSharp
Jiranet : Refers to .NET

**Comment by kalhorim** [comment]
Thank you, @mtss92,
I prefer to use 
**AtlassianAssistance**
do you accept it?

**Comment by mtss92** [comment]
Atlassian is a general concept and includes all the software of this company. But this library is only used for Jira.
My suggestion is: 
JiraAssistance
